server:
  port: 9090
spring:
  datasource:
    username: root
    password: "010311"
    url: jdbc:mysql://localhost:3306/biyeku?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis:
  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
alipay:
  appId: 2021000122673013
  appPrivateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCm+msVT+FtTlVV94lBsSQ7ORnUBOh3Z+El16hDUXvmvbhEIxHsH4F2kNOTgT/0Du+6Eqq6eabJ3r6ecCx7jYKxRhLpUyCDMmLWktcftektUH7dwYYY1v7bBC5jl3VjrucnVCYr/237RmypPfgqmf6fED4a4KomKKHX4A29v5/YKdn1jqaLC9aYK3/4K8WMFo4yM20kHmZROAJC5j5UEeT7oL/e2fnwvugg5kK+h0n7ZG4KK1N6ljlLt1kXQWej9d/oZtXQq1unlnjDUKZsB+91hmSseB+jrvdOOR4stvKOxAazhWUtMVWp/x7zY0/FZVVMgit0lsdZ0K7dkWNE3+G3AgMBAAECggEAY3plOXkxj/FPHbwvZZenQjEulgWmiRy2IdltQU3WRw1YLh/Gmanbc0utAP/LnhcX8v8T/6xiFXpCjhm+Jo2UAxEAS0le4UqvX65zw0yY8oo2St70iO/tPYYsLOEa6pxU0jVr2GKAn2bBbcKhip/b9d+zYEfgloM2iGnPRfBXxmuOaAsMLW7EqRn5N4z1hkCHhBlUC3ShH5E60VCF6yK9w9nQEXpB/XQPZnqGtv8ILAsqRC4B8BquXQs8EQlg0zU8dlzexC4noV/ZQQPIQsFh0Yu0syIkEB3IzhxueIJAZ2BZHPQsHbz+6xv34z2sM7x9O29C9katPMqYID1loQk8AQKBgQD2e5dXNCcMq1rBc7oqJ2aV6NDHvo/nlvN00mBxBKB3A1vmAmdCkSbDTaQLYS3tSg04DxINFBhFlAknSybDmi4cyt0c0SzFK3OAzm+qp7mjWdXax+ZVWxyuRZdEWRR0X/zRc0DE1XNaMWV7gPY0cEdD3VijAf12C3cd5A8ciMl+gQKBgQCtbPKxSx/xWEaQ7Nam4sXAtTl4ElWhqRLjtYed3kUgZmyjPD1LttZmleARU2XMjmJ5JuwFFOwqy65YN8F1Fp4x37Zulezs4Q+R2ZHmt12BTZ2P2pxkHX6wFF+tQtuimeIxNB3bKC+Dj7aZdbG++oaF7ywPsHUMkazbTyElaSO0NwKBgQCM8y4fQwaVmyPB/pDV7EQgs8s4fkPClrLP+kIGPzQX+sbBqFwuV90H0E1f6Imf6TnX9d5HtlcO6tG1M6eOMYvvER8SjJeChQ9++A4pU9K3k/bULn4MD5c+HTOcdShaSE3F5JeEN9/IEvlKf/vLDu3h5CD8znWH3JSYdkMh+SLogQKBgEs1VSZH4wlh8/BDlW74JzREIzEMGnCqBtQTVEXFL4s2f+RmalqcZuxEENDSrvH/yXqqw24MvcJtZCVDwLTLYz1TvCTHBeFQVNU2WkyItpctlqfc8TeFhvxLSZa0yNUCERKvfEcfbUOLnm98l+GveYk5yIzhRFF4F1NgRIqZxu8PAoGBAKsLhAh/XVP6qx8hBK+KWHT/NhhgO757J5w0++NILZHhHaLIUR6nb3alj1xSKpaR/I+NrpkuCUJmlif9QcmhbirQIE85golUVAPMTcbdtUcqh95clGtFtquX/RcGTkUcCw+tA78bnCtBFMcL6mOdsyETnhDMKcHLXfjyE+Mughy6
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlCJhyKTS0l1juuZaalra33GTRNS4Sq+LPIri/N2zCRV6s083RGcPFTEp2XRkm/hUOja35pC3xjPeEF608QrBjJFUOQ6qBcFwuHL1EGDttAlW677qP4/ui+PtR+ybfaJryJlRMvYgWbvcZqeC2/Ufha2OktdKZ4vYZwTwOd2QgNqDp5izFETPeYbZsGarvWmXcb8V3bJJIT2YUDGf8HdZUEuHhB58v9gyt41EQhetao2391xCUXOGKuEC10aqIf328c4Tr7i7KLgeTPTRhgMoNNBYSore3NdphMZx+rEOY1f6sO3tvNjIopqLVljcPZosQ/+f6BMzZxj/swIqwotQvwIDAQAB
  notifyUrl:     http://izp5dx.natappfree.cc/alipay/notify




